### PR TITLE
bug didn't create work or object in influenced triples

### PR DESCRIPTION
**Pull request by kkdavis14**
caused creation of this triple "https://lux.collections.yale.edu/ns/linguisticobjectInfluencedCreation"

See https://github.com/project-lux/lux-marklogic/issues/357

### CODE REVIEW

**Comment by azaroth42** [comment]
typ.lower() still needs to be called to turn `Place` in to `place`

**Comment by kkdavis14** [comment]
@azaroth42 PR is ready for re-review

**Comment by azaroth42** [comment]
Also needs to call the new function for the referenced records :)

**Comment by kkdavis14** [comment]
@azaroth42 it calls it at line 183--is that not sufficient? it seems like pfx is only the record we're on/only one at a time and doesn't need created multiple times.

**Comment by azaroth42** [comment]
Also circa 280 and 320 to avoid calculating `typ` in different ways

**Comment by kkdavis14** [comment]
@azaroth42 oh yeah for the actual reason of this ticket :D also added it in a few other places typ was being created.

**Comment by azaroth42** [comment]
Perfect, thank you!

**Pull request merged**
